"""add whatsapp broadcast tables

Revision ID: 26b6a3712c3b
Revises: d1e2f3a4b5c6
Create Date: 2026-08-21 15:14:12.037041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26b6a3712c3b'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_events_external_event_id'), 'whatsapp_events', ['external_event_id'], unique=True)
    op.create_table('whatsapp_broadcasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('group_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENDING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', name='broadcaststatus'), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broadcast_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('external_message_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='whatsappmessagestatus'), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['whatsapp_broadcasts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_broadcast_id'), 'whatsapp_messages', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_external_message_id'), 'whatsapp_messages', ['external_message_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_messages_user_id'), 'whatsapp_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_user_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_external_message_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_broadcast_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_table('whatsapp_broadcasts')
    op.drop_index(op.f('ix_whatsapp_events_external_event_id'), table_name='whatsapp_events')
    op.drop_table('whatsapp_events')
    # ### end Alembic commands ###
