"""add product snapshot fields to messages

Revision ID: 783405f4a5f9
Revises: c7d75aa04b51
Create Date: 2026-08-11 15:12:31.018270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783405f4a5f9'
down_revision: Union[str, Sequence[str], None] = 'c7d75aa04b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('product_name', sa.String(length=200), nullable=True))
    op.add_column('messages', sa.Column('product_image', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('product_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'product_description')
    op.drop_column('messages', 'product_image')
    op.drop_column('messages', 'product_name')
    # ### end Alembic commands ###
