"""add click attribution to whatsapp messages

Revision ID: 8abf07bd73b2
Revises: 26b6a3712c3b
Create Date: 2026-08-21 15:55:12.382382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abf07bd73b2'
down_revision: Union[str, Sequence[str], None] = '26b6a3712c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('whatsapp_broadcast_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_messages_whatsapp_broadcast_id'), 'messages', ['whatsapp_broadcast_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'whatsapp_broadcasts', ['whatsapp_broadcast_id'], ['id'])
    op.add_column('whatsapp_messages', sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_messages', 'clicked_at')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_whatsapp_broadcast_id'), table_name='messages')
    op.drop_column('messages', 'whatsapp_broadcast_id')
    # ### end Alembic commands ###
