"""add quantity_in_bundle to products

Revision ID: de74befd8d99
Revises: 8abf07bd73b2
Create Date: 2026-08-21 18:19:32.264729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de74befd8d99'
down_revision: Union[str, Sequence[str], None] = '8abf07bd73b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity_in_bundle', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity_in_bundle')
    # ### end Alembic commands ###
